// Convert string to rows
// Allowed time: 45 mins

// You are given a string str which is generated by breaking it down into rows and writing in a zigzag pattern. For example, the string PAYPALISHIRING is written in a zigzag pattern for 3 rows, it will look like this:

// P   A   H   N
// A P L S I I G
// Y   I   R
// In the above example, if you start from P, go downwards till Y, then go diagonally to A and back down to I and so on until the end of the sequence, you'll find the string PAYPALISHIRING.

// These rows, read line by line, will equal to the string PAHNAPLSIIGYIR, ignoring the whitespaces.

// Your task is to write a function convertToRows which takes a string str and number n which is number of rows and returns the string can be written in zigzag manner and read the original str

// Examples:

function convertToRows(string, rows){
    let result = ""
    let subString = "";
    let subString3 = "";
    let arr = [];
    let arr2 = [];
    if (rows ===3){
    for(let i = 0; i < string.length; i++){
        if(i === 0 || i === 4 ||i === 8 ||i === 12){
            arr.push(string[i]);
        }
        else if(i%2 !== 0){
            subString= subString+string[i];
        }
        else{
            arr2.push(string[i]);
        }
    }
    let subString1 = arr.join(" ");
    let subString2 = arr2.join(" ");
    result = result + subString1 +"\n" + subString + "\n" + subString2;
    return result;
}
else if(rows===4){
    let len = string.length;
    
    let rowLength = Math.floor(len/rows);
    console.log(rowLength);
    for(let i = 0; i < string.length; i++){
        if(i === 0 || i === 6 ||i === 12){
            arr.push(string[i]+"  ");
        }
        else if(i%2 !== 0 && i !== 3 && i !== 9){
            subString= subString+string[i]+" ";
        }
        else if(i%2===0){
            arr2.push(string[i]+" ");
        }
        else{
            subString3= subString3+string[i]+"    ";
        }
    }
    let subString1 = arr.join(" ");
    let subString2 = arr2.join(" ");
    result = result + subString1 +"\n" + subString + "\n" + subString2 + "\n"+ subString3;
    return result;

}
}

console.log(convertToRows("PAYPALISHIRING", 3)); // should return "PAHNAPLSIIGYIR"
console.log(convertToRows("PAYPALISHIRING", 4)); // should return "PINALSIGYAHRPI"
// P     I    N
// A   L S  I G
// Y A   H R
// P     I